---
layout: post
title: Evolution of inbreeding
author: Brad Duthie
published: false
status: process
draft: false
tags: R
output: md_document
bibliography: duthie.bib
---

It is widely under-appreciated that active inbreeding -- and especially *biparental* inbreeding -- can be adaptive and therefore favoured by natural selection. Biparental inbreeding specifically refers to the situation in which two different, but genetically related, organisms breed and thereby produce inbred offspring. This situation differs from self-fertilisation, in which an organism inbreeds with itself, as is perhaps most commonly studied in plants [e.g., Barrett1996; @Vogler2001]. The addition of a second parent complicates how inbreeding will affect individual fitness, partly because we have -- by definition -- two different individuals to consider (a female and a male), but also because biparental inbreeding can occur between any number of different types of relatives (e.g., siblings, cousins, etc.). I'll explain these complications in more detail below, but first I want to note two important general points about inbreeding, the combination of which makes the evolution of inbreeding particularly interesting. 

The first point is that individuals that inbreed typically produce offspring that have lower fitness than individuals that outbreed (e.g., they have offspring with a lower probability of survival), a phenomenon called ''inbreeding depression''. That inbreeding depression occurs is well-known, and I won't get into the details of what causes it [see @Charlesworth1999; @Charlesworth2009]. The second point is that despite the occurrence of inbreeding depression in inbred **offspring**, this does not necessarily mean that inbreeding **parents**  themselves have lower fitness than parents that avoid inbreeding. This second point isn't intuitive, and was first articulated by Geoff @Parker1979 for the case of biparental inbreeding.


Parker's model of biparental inbreeding
----------------------------------------------------

The foundational work of biparental inbreeding theory developed by [Parker](https://en.wikipedia.org/wiki/Geoff_Parker) appears as a chapter in [*Sexual Selection and Reproductive Competition in Insects*](https://www.amazon.co.uk/Sexual-Selection-Reproductive-Competition-Insects/dp/0124145760) [@Parker1979] [[1]](#foot1). @Parker1979 considered an encounter and the subsequent reproductive decisions of two focal relatives [[2]](#foot2). Below, I'll show the logic of these reproductive decisions first for females, then for males.

Consider a focal female that can produce $n$ offspring -- the exact number doesn't matter for demonstrating the key point, so to keep things simple, we can start by assuming that this number will always be the same. This focal female encounters a first cousin, and upon the encounter must decide whether or not to inbreed with him. If she does not inbreed with him, then we'll assume that she is able to find some other male to breed with to whom she is not related. By avoiding inbreeding with her cousin and outbreeding instead, she will produce $n$ offspring that do not suffer any inbreeding depression. For simplicitly, we can set their fitness to a value of $1$, and think of this value as the probability that an outbred offspring survives to adulthood. If she instead inbreeds with her cousin, then she will produce $n$ offspring whose survival probability will be reduced by some value $\delta$ due to inbreeding depression. Hence, if the focal female outbreeds, then she will produce $n$ offspring with a survival probability of $1$. And if she inbreeds with her cousin, then she will produce $n$ offspring with a survival probability of $(1 - \delta)$. If we only consider the effects of inbreeding depression, then the $n \times 1$ surviving offspring that the focal female produces by outbreeding will always be favoured by selection over the $n \times (1 - \delta)$ surviving offspring produced by inbreeding, and the inequality

n (1 - $\delta$) > n,

will never be true.

But the above inequality leaves out something important to inbreeding that affects fitness. **If the focal female chooses to inbreed with her cousin, then his reproductive success will be increased**. Hence, by inbreeding, she can increase the reproductive success of her relative, and thereby increase her fitness indirectly -- by how much depends on her *relatedness* to her potential mate. Assuming the focal female is herself outbred (i.e., that her own parents did not inbreed), then her cousin's relatedness to her will be $1/8$ [[3]](#foot3). She should therefore consider any additional reproductive success of her cousin that results from her decision with $1/8$ the weight of her own reproductive success. The indirect fitness accrued from the reproductive success of her cousin plus the direct fitness accrued from her own reproductive success defines her *inclusive fitness* as accrued through her reproductive decision; inclusive fitness, more generally, can be used to determine how selection will act on a particular behaviour [@Hamilton1964; @Grafen2006]. In the case of inbreeding, we can contrast the inclusive fitness accrued from inbreeding with that of outbreeding,

n (1 - $\delta$) + $1/8$ n (1 - $\delta$) > n.

Now, note that the above inequality isn't always false -- as it obviously was in the first inequality when indirect fitness was not taken into account. If we now imagine a very small value of $\delta$, then the left hand side of the above inequality will approach a value of $n + (1/8)n$, higher than the inclusive fitness of outbreeding ($n$). Yet a large value (close to 1) of $\delta$ will make the left hand side closer to zero. Whether inbreeding or avoiding inbreeding yields the highest inclusive fitness therefore clearly depends on the value of $\delta$. In fact, we can calculate the threshold value below which inbreeding increases inclusive fitness by isolating the above equation for $\delta$,

n (1 - $\delta$) + $1/8$ n (1 - $\delta$) > n

(1 - $\delta$) + $1/8$ (1 - $\delta$) > 1

1 - $\delta$ + $1/8$ - $1/8$ $\delta$ > 1

1 + $1/8$ > 1 + $\delta$ + $1/8$ $\delta$

$1/8$ > $\delta$ + $1/8$ $\delta$

$1/8$ > (1 + $1/8$) $\delta$

$1/8$ / (1 + $1/8$) > $\delta$

$1/9$ > $\delta$.

In our example, a focal female will increase her inclusive fitness more by inbreeding with her cousin than by avoiding inbreeding with him if $\delta$ is less than one ninth -- or, put differently, if her inbred offspring have an $8/9$ survival probability. **A focal female can thereby increase her inclusive fitness if inbreeding depression is sufficiently weak**.

We can consider the same interaction from the perspective of the male, encountering a cousin and deciding whether or not to inbreed with her. The key difference from the perspective of the focal male is that inbreeding *directly* increases his own reproductive success, yielding a higher inclusive fitness overall. Given stereotypical sex roles, the reproductive success of the focal male is limited only by the number of mates that he can acquire. In other words, while a focal females is always limited to producing $n$ offspring, the number of offspring that a focal male sires increases with every new mating.

Inbreeding therefore increases a focal male's inclusive fitness directly, instead of indirectly as is the case for focal females. This direct component is $n (1 - $\delta$)$ -- number of offspring produced scaled by inbreeding depression. The focal male also receives an indirect component of $1/8$ n (1 - $\delta$)$, which represents the direct fitness of the focal male's cousin scaled to his relatedness to her ($1/8$). Note that the inclusive fitness accrued from inbreeding is the same for the focal male as it was for the focal female, the direct plus indirect components of inclusive fitness are $n (1 - $\delta$) + 1/8$ n (1 - $\delta$)$, which can be re-written as $n(1+1/8)(1-\delta)$. But if the focal male avoids inbreeding, he has missed out on the chance to produce additional offspring -- the only consolation is that the cousin he avoided inbreeding with will then outbreed and produce healthy related offspring that benefit him indirectly (note, the focal male might go off and mate with other females, but, given stereotypical sex roles, we're assuming that he could have done so even if he had chosen to inbreed). His inclusive fitness resulting from the decision to avoid inbreeding is therefore $(1/8)n$ -- i.e., his cousin's inclusive fitness scaled to his relatedness to her. We can contrast the inclusive fitness accrued from inbreeding with that of outbreeding for the focal male, as we did for his cousin,

n (1 - $\delta$) + $1/8$ n (1 - $\delta$) > $1/8$ n.

Note again, the only difference here is the right-hand side of the inequality (representing inbreeding avoidance), which is now $1/8 n$ to reflect the indirect component of inclusive fitness from avoiding inbreeding. As with the focal female, we can solve for $\delta$ to identify the threshold value below which inbreeding yields a higher inclusive fitness than avoiding inbreeidng,

n (1 - $\delta$) + $1/8$ n (1 - $\delta$) > $1/8$ n

(1 - $\delta$) + $1/8$ (1 - $\delta$) > $1/8$

1 - $\delta$ + $1/8$ - $1/8$ $\delta$ > $1/8$

1 + $1/8$ - $1/8$  > $\delta$ + $1/8$ $\delta$

1 > $\delta$ + $1/8$ $\delta$

1 > $\delta$(1 + $1/8$)

1 / (1 + 1/8) > $\delta$

$8/9$ > $\delta$.

Here, the focal male increases his inclusive fitness more by inbreeding with his cousin that by avoiding inbreeding with her if $\delta$ is less than eight ninths -- or if his inbred offspring have a $1/9$ probability of survival. Not only does this demonstrate that a focal male can increase his inclusive fitness by inbreeding, it shows that his threshold value of inbreeding upon encountering a cousin is considerably higher than hers. **Consequently, sexual conflict over inbreeding is predicted during such an encounter; a focal male will increases his inclusive fitness by inbreeding, while a focal female will increase her inclusive fitness by avoiding inbreeding.** In the case of the two cousins, such a conflict is predicted when inbreeding depression satisfies $1/9 < \delta < 8/9$. 

General theoretical insights of Parker's model
----------------------------------------------------

The theoretical insights provided by this simple model are general to encounters between females and males of any given relatedness $r$: 

> **Natural selection should make inbreeding between females and males adaptive given sufficiently low inbreeding depression in the fitness of their offspring, and females and males will typically disagree over how low inbreeding depression should be before inbreeding is adaptive (generating sexual conflict over inbreeding)**

The generality of these two key insights of @Parker1979 can be shown by simply substituting a specific value of relatedness ($1/8$, in our example with cousins). The general inequality predicting whether or not a focal female's inclusive fitness increases by inbreeding is thereby modelled as,

n(1+r)(1-$\delta$) > n.

From the above, the general threshold of $\delta$ below which a focal female increases her inclusive fitness can be written as,

\delta <   r / (1 + r).

The equivalent general inequality predicting male predicting whether or not inbreeding increases inclusive fitness in males is,

n(1+r)(1-$\delta$) > rn.

For the above, we get the general threshold $\delta$,

\delta <   1 / (1 + r).

We can plot this threshold $\delta$ over a range of $r$ values for both females and males [as appears in @Waser1986; @Puurtinen2011; @Szulkin2012; @Duthie2015a].

![Threshold inbreeding depression values below which inbreeding increases female and male inclusive fitness for different relatedness values, as recreated from Duthie and Reid (2015). The x-axis shows the relatedness (r) between two focal potential mates, and the y-axis shows the magnitude of inbreeding depression below which inbreeding is beneficial for each sex. The white shaded region shows where neither sex benefits by inbreeding, the black shaded region shows where only males benefit by inbreeding (sexual conflict), and the grey shaded region shows where both females and males benefit by inbreeding.](figures/unnamed-chunk-1-1.png)


Why and how Parker's insights are still relevant
----------------------------------------------------

The general equation identifying inbreeding depression thresholds for females and males appears in various forms in subsequent theoretical papers including, @Waser1986, @Lehmann2003, @Parker2006, @Kokko2006, @Puurtinen2011, @Szulkin2012, @Duthie2015a, @Lehtonen2015, and @Duthie2016b. Each of these papers builds off of the foundational work of @Parker1979 in different ways to develop new theoretical insights, clarify existing insights, or unify inbreeding theory with other theory in evolutionary ecology. I'll save these insights for a future post, and for now just note that **the inbreeding depression thresholds of the above model need to be interpreted with caution.** The greatest importance of @Parker1979 was to provide the two general theoretical predictions mentioned above. @Parker1979 did this by showing how these two predictions follow logically from a small number of useful biological assumptions, thereby demonstrating how to think more clearly about inbreeding and inbreeding avoidance in and across natural systems. It is this greater clarity of thought that is most relevant for developing empirical hypotheses, not the specific numerical predictions of inbreeding depression thresholds derived from the above inequalities (as see in the figure above). Subsequent theory papers by, e.g.,  @Waser1986, @Kokko2006, and @Duthie2015a build off of @Parker1979 to show that the numerical values of these thresholds will change depending on additional assumptions about interacting females and males (in addition to providing other insights).

Some biological assumptions are expected to apply to all, or nearly all, biological systems. As a theoretician, it is perhaps most exciting to discover novel predictions that follow from these universal assumptions [[4]](#foot4), and to thereby develop theory of the most general relevance that conceptually unifies across the biological sciences. But biological systems vary widely, making it is necessary to also vary the assumptions of our models when deriving specific -- and particularly *quantitative* -- predictions. A lot of important biological assumptions about interacting females and males will vary among species (e.g., as a consequence of different life histories), and these assumptions will be relevant for predicting the specific conditions under which inbreeding versus inbreeding avoidance will be adaptive for any paricular species. Understanding which assumptions are most applicable for deriving system-specific hypotheses about inbreeding therefore requires a strong understanding of the natural history of a species. **To develop clear hypotheses about biparental inbreeding in a specific system, it is therefore necessary draw from a broad understanding of the theoretical literature on inbreeding and apply it to the specific natural history of a biological system.**

<!--- Get a better ending here? --->


********************************************************************************

<a name="foot1">[1]</a> As an aside, this is a wonderful book that also includes a chapter written by Bill Hamilton on wing dimorphism in male fig wasps, likening male-male competition within a fig to ''a darkened room full of jostling people among whom, or else lurking in cupboards and recesses which open on all sides, are a dozen or so maniacal homicides armed with knives'' [@Hamilton1979 p. 173].

<a name="foot2">[2]</a> @Parker1979 considered an encounter between a female and her full-sibling brother. I'm going to use cousins to deliberately produce an example with a different numerical result.

<a name="foot3">[3]</a> Specifically, her *coefficient of relatedness*; see, e.g., @Michod1979 or @Duthie2015a for more detail on how *relatedness* is calculated, particularly given inbreeding.

<a name="foot4">[4]</a> Or, perhaps equally appealing, to discover previously unknown assumptions from consistently observed patterns (predictions) -- or to discover new and interesting paths by which the two are logically connected.

********************************************************************************

References
----------------------------------------------------------------




